import React from 'react';
import Step from './Step';

export default function Information() {
    return (
        <div className='infoDiv'>
            <h1>Calculate the estimated emissions on your Azure IaaS resources</h1>
            <p>Are you seeking a deeper understanding of the emissions generated by your Azure IaaS resources?
                Perhaps you're interested in comparing estimated emissions across various resources. This calculator is designed to provide valuable insights,
                enabling you to make informed choices and identify the most suitable solutions.
                Additionally, it can highlight significant contributors, empowering you to strategically reduce emissions in your operations.</p>

            <div className='allStepsDiv'>
                <Step />
                <Step />
                <Step />
            </div>
            
        </div>
    );
}